# Generated by Django 2.2.3 on 2019-07-26 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('tour_date_and_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Tours',
            },
        ),
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
