# Generated by Django 2.2.3 on 2019-08-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190728_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
            options={
                'verbose_name_plural': 'TourPackages',
            },
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='images/placeholderImage.png', upload_to='images/'),
        ),
    ]
