# Generated by Django 2.2.3 on 2019-08-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190802_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
